### ISSUE TITLE
Use Summation-By-Parts differencing operators

### ISSUE THREAD

**Issue by eschnett** [anilzen/NullPaper#10]
I think that the finite differencing operators currently implemented are e.g. everywhere second order accurate, including at the boundary. If you used FD operators instead that satisfy Summation-By-Parts (SBP), then it would be easier to obtain a stable discretization. [This paper](https://arxiv.org/abs/gr-qc/0512001) (shameless self advertisement) derives and tables such operators.

The basic idea behind SBP is that integration by parts holds in the discrete, independent of the resolution. This is convenient because: If you have a conserved energy in the continuum (with a few additional, technical properties), then your hyperbolic system is well-posed. If you discretize that system using SBP operators, then the same proof will often also hold in the discrete, giving you a stable discretization. (I'd be happy to discuss.)

The SBP FD operators look the same in the interior, but look different at the boundary. The usually are slightly less accurate there, but the stability guarantee outweighs this.

**Comment by anilzen** [comment]
Tests.ipynb show that the finite difference operators have the correct order (2, 4, and 6). But I agree that SBP operators would be helpful to ensure the stability of a hyperbolic system. This repository is primarily concerned with boundary value problems (in particular, the unbounded-domain Helmholtz equation with Dirichlet conditions at the inner boundary). So I think SBP operators are not necessary in this case.
